spring.application.name=main-api

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/nutrifit
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# JPA
spring.jpa.hibernate.ddl-auto=validate

# RSA Keys
rsa.public-key=${RSA_PUBLIC_KEY:classpath:certs/public.pem}
rsa.private-key=${RSA_PRIVATE_KEY:classpath:certs/private.pem}

# JWT
jwt.access-token-expiry-seconds=900

# CORS
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}

# Cookies
app.cookie.secure=${APP_COOKIE_SECURE:true}

# ML API
ml-api.base-url=${ML_API_BASE_URL:http://localhost:8000}

# Frontend
app.frontend.url=${APP_FRONTEND_URL:http://localhost:5173}

# Mail
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
