spring.application.name=main-api

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/nutrifit
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# JPA
spring.jpa.hibernate.ddl-auto=validate

# RSA Keys
rsa.public-key=classpath:certs/public.pem
rsa.private-key=classpath:certs/private.pem

# JWT
jwt.access-token-expiry-seconds=900

# CORS
cors.allowed-origins=http://localhost:5173

# Cookies
app.cookie.secure=${APP_COOKIE_SECURE:true}
